### ISSUE TITLE
Won't change button text color.

### ISSUE THREAD

**Issue by gilbster** [marscollective/link-free#103]
**Describe the bug**
When Editing the color of the button from the admin pages, I can change the color of the button, but not the color of the button's text.

**To Reproduce**
1. Go to '/admin'
2. Click on 'Index'
3. Scroll down to 'Font Color' and select a color.
4. After Publishing, nothing changes.

**Expected behavior**
I would expect the text color of the button to change, but it seems to stay dark.

**Comment by dsoaress** [comment]
Thanks for reporting. The [error has been corrected](https://github.com/marscollective/link-free/commit/323441a245a71379a8ee6646926df0d249196cb3#diff-f663c3b535aec4b8b3e4a19be29034926e9e9c172049a31512aa91db6e20a004).
